// Code generated by gotestmd DO NOT EDIT.
package basic_interdomain

import (
	"github.com/stretchr/testify/suite"

	"github.com/networkservicemesh/integration-tests/extensions/base"
	"github.com/networkservicemesh/integration-tests/suites/basic_interdomain/examples/basic_interdomain/dns"
	"github.com/networkservicemesh/integration-tests/suites/basic_interdomain/examples/basic_interdomain/loadbalancer"
	"github.com/networkservicemesh/integration-tests/suites/basic_interdomain/examples/basic_interdomain/nsm"
	"github.com/networkservicemesh/integration-tests/suites/basic_interdomain/examples/basic_interdomain/spire"
	"github.com/networkservicemesh/integration-tests/suites/nsm_consul"
	"github.com/networkservicemesh/integration-tests/suites/nsm_istio"
)

type Suite struct {
	base.Suite
	loadbalancerSuite loadbalancer.Suite
	dnsSuite          dns.Suite
	spireSuite        spire.Suite
	nsmSuite          nsm.Suite
	nsm_istioSuite    nsm_istio.Suite
	nsm_consulSuite   nsm_consul.Suite
}

func (s *Suite) SetupSuite() {
	parents := []interface{}{&s.Suite, &s.loadbalancerSuite, &s.dnsSuite, &s.spireSuite, &s.nsmSuite}
	for _, p := range parents {
		if v, ok := p.(suite.TestingSuite); ok {
			v.SetT(s.T())
		}
		if v, ok := p.(suite.SetupAllSuite); ok {
			v.SetupSuite()
		}
	}
	s.RunIncludedSuites()
}
func (s *Suite) RunIncludedSuites() {
	runTest := func(subSuite suite.TestingSuite, suiteName, testName string, subtest func()) {
		type runner interface {
			Run(name string, f func()) bool
		}
		defer func() {
			if afterTestSuite, ok := subSuite.(suite.AfterTest); ok {
				afterTestSuite.AfterTest(suiteName, testName)
			}
			if tearDownTestSuite, ok := subSuite.(suite.TearDownTestSuite); ok {
				tearDownTestSuite.TearDownTest()
			}
		}()
		if setupTestSuite, ok := subSuite.(suite.SetupTestSuite); ok {
			setupTestSuite.SetupTest()
		}
		if beforeTestSuite, ok := subSuite.(suite.BeforeTest); ok {
			beforeTestSuite.BeforeTest(suiteName, testName)
		}
		// Run test
		subSuite.(runner).Run(testName, subtest)
	}
	s.Run("Nsm_consul", func() {
		s.nsm_consulSuite.SetT(s.T())
		s.nsm_consulSuite.SetupSuite()
	})
	s.Run("Nsm_istio", func() {
		s.nsm_istioSuite.SetT(s.T())
		s.nsm_istioSuite.SetupSuite()
	})
}
func (s *Suite) Test() {}
